# Generated by Django 5.1.1 on 2024-10-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='Default_pfp.png', null=True, upload_to=''),
        ),
    ]
