# Generated by Django 5.1.1 on 2024-11-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_chatgroup_is_private_chatgroup_members_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='GroupMessage',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='users_online',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
